core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from store import views


urlpatterns = [
    path('J8eycqM5bRg2pN/', admin.site.urls),
    path('store/', include('store.urls')),
    # default route to store app
    path('', views.IndexView.as_view(), name='index'),
    path('accounts/', include('accounts.urls')),
]
if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),

    ] + urlpatterns
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/store/urls.py
from django.urls import path, re_path

from . import views
app_name = 'store'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('articles', views.articles, name='articles'),
    path('article/<int:article_id>/', views.article_detail, name='detail'),
    path('create_article', views.create_article, name='create_article'),
    path('create_object', views.create_object, name='create_object'),
    path('create_couleur', views.create_couleur, name='create_couleur'),

    re_path(r'^categories/$', views.CategorieView, name='categories'),
    # ex: /polls/5/results/

]

core/store/models.py
from django.db import models

from django.db import models
import barcode                      # additional imports
from barcode.writer import ImageWriter
from io import BytesIO
from django.core.files import File
from django.db import models


# Register your models here.


# question = models.ForeignKey(Question, on_delete=models.CASCADE)*


# exemple vetement, chaussure, bijoux
class Categorie(models.Model):
    name = models.CharField(max_length=30)
    image = models.ImageField(
        upload_to='images_categorie/', blank=True, null=True)

    def __str__(self):
        return self.name


class Couleur(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

# exemple XS, ml, cm, 90


class Taille(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


# exemple pull, boucle d'oreille, pantalon


class Object(models.Model):
    name = models.CharField(max_length=30)
    type = models.ForeignKey(Categorie, on_delete=models.CASCADE)
    image = models.ImageField(
        upload_to='images_objects/', blank=True, null=True)

    def __str__(self):
        return self.name


class Article(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(
        max_length=300, default="", blank=True, null=True)
    couleur = models.ForeignKey(Couleur, on_delete=models.CASCADE)
    prix = models.FloatField()
    image = models.ImageField(
        upload_to='images_articles/', blank=True, null=True)
    object = models.ForeignKey(Object, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Stock(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    taille = models.ForeignKey(Taille, on_delete=models.CASCADE)
    quantite = models.IntegerField()
    code128 = models.CharField(
        max_length=128, default="", blank=True, null=True)  # code 128
    barcode = models.ImageField(
        upload_to='barcodes/', blank=True, null=True)

    def save(self, *args, **kwargs):          # overriding save()
        COD128 = barcode.get_barcode_class('code128')
        rv = BytesIO()
        code = COD128(
            f'{self.article.object.type.name[0:2]+self.article.object.name[0:2]+self.article.name[0:2]+self.article.couleur.name[0:2]+self.taille.name + str(self.pk)}', writer=ImageWriter()).write(rv)
        self.code128 = code
        self.barcode.save(f'{code}.png', File(rv), save=False)
        return super().save(*args, **kwargs)

    def __str__(self):

        return self.article.name + "_" + self.taille.name

# créole blanche, pull lacoste, pantalon noir

core/store/forms.py
from .models import Article, Couleur, Object
from django.forms import ModelForm
from django import forms


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['name', 'description', 'object', 'couleur',
                  'prix', 'image']


class ObjectForm(ModelForm):
    class Meta:
        model = Object
        fields = ['name', 'type', 'image']


class CouleurForm(ModelForm):
    class Meta:
        model = Couleur
        fields = ['name']

core/store/views.py
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic.list import ListView

from .forms import ArticleForm, CouleurForm, ObjectForm

from .models import Couleur, Object, Stock, Article, Categorie
from django.views import generic
from django.contrib.auth.decorators import login_required


class IndexView(generic.ListView):
    template_name = 'store/index.html'
    model = Article

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in the publisher
        context['vetements'] = Article.objects.filter(
            object__type__name="vetement").order_by('-created_at')[:12]
        context['cosmetiques'] = Article.objects.filter(
            object__type__name="cosmetique").order_by('-created_at')[:12]
        context['bijoux'] = Article.objects.filter(
            object__type__name="bijoux").order_by('-created_at')[:12]
        context['enfants'] = Article.objects.filter(
            object__type__name="enfant").order_by('-created_at')[:12]

        return context


def CategorieView(request):
    categorie = request.GET['categorie']
    context = {}
    liste_categories = [
        categorie__tmp.name for categorie__tmp in Categorie.objects.all()]
    if categorie in liste_categories:
        context["categorie"] = categorie
        context["background"] = Categorie.objects.get(name=categorie).image
        context['articles'] = Article.objects.filter(
            object__type__name=f"{categorie}").order_by('-created_at')

        if("type" in request.GET.keys()):
            context['articles'] = context['articles'].filter(
                object__type__id=request.GET['type'])

        if("couleur" in request.GET.keys()):
            context['articles'] = context['articles'].filter(
                couleur__id=request.GET['couleur'])

        context['objects'] = Object.objects.filter(
            type__name=categorie).order_by('name')

        context['couleurs'] = Couleur.objects.all()
    else:
        return HttpResponseNotFound()

    return render(request, 'store/categorie.html', context)


def articles(request):
    articles = ["<li>{}</li>".format(article.name)
                for article in Article.objects.all()]
    message = """<ul>{}</ul>""".format("\n".join(articles))
    return HttpResponse(message)


def article_detail(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    sizes = Stock.objects.filter(article=article).values_list(
        'taille__name', flat=True).distinct()
    #
    return render(request, 'store/detail.html', {'article': article, 'sizes': sizes})


# <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>

def sort_size(sizes):

    SORT_ORDER = {"XS": -1, "S": 0, "M": 1, "L": 2, "XL": 3,
                  "2XL": 4, "3XL": 5, "4XL": 6, "5XL": 7, "6XL": 8}
    return sorted(
        sizes, key=lambda elem: SORT_ORDER[elem])


@login_required
def create_article(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('store:index')
    else:
        form = ArticleForm()
    return render(request, 'store/create.html', {'form': form})


@login_required
def create_object(request):
    if request.method == 'POST':
        form = ObjectForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('store:index')
    else:
        form = ObjectForm()
    return render(request, 'store/create.html', {'form': form})


@login_required
def create_couleur(request):
    if request.method == 'POST':
        form = CouleurForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect('store:index')
    else:
        form = CouleurForm()
    return render(request, 'store/create.html', {'form': form})

core/store/templates/store/base.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    {% load static %}

    <title>3and Linda</title>
    <link rel="icon" type="image/x-icon" href="{% static 'store/images/favicon.svg' %}">


    <!-- Additional CSS Files -->
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Tangerine&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'store/css/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'store/css/font-awesome.css' %}">

    <link rel="stylesheet" href="{% static 'store/css/templatemo-hexashop.css' %}">

    <link rel="stylesheet" href="{% static 'store/css/owl-carousel.css' %}">

    <link rel="stylesheet" href="{% static 'store/css/lightbox.css' %}">
<!--

TemplateMo 571 Hexashop

https://templatemo.com/tm-571-hexashop

-->
    </head>
    
    <body>
    
    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->
    
    
    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="{% url 'store:index' %}" class="logo_update">
                            <img src="{% static 'store/images/logo_carre.png' %}">
                        </a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            {% if categorie %}
                            <li class="scroll-to-section"><a href="{% url 'store:index' %}">Accueil</a></li>
                            {% elif not categorie and not connection %}
                            <li class="scroll-to-section"><a href="{% url 'store:index' %}" class="active">Accueil</a></li>
                            {% else %}
                            <li class="scroll-to-section"><a href="{% url 'store:index' %}">Accueil</a></li>
                            {% endif %}
                            {% if categorie == "vetement" %}
                            {% endif %}
                            {% if categorie == "vetement" %}
                            <li class="scroll-to-section"><a href="/store/categories?categorie=vetement" class="active">Vêtements</a></li>
                            {% else %}
                            <li class="scroll-to-section"><a href="/store/categories?categorie=vetement">Vêtements</a></li>
                            {% endif %}
                            {% if categorie == "cosmetique" %}
                            <li class="scroll-to-section"><a href="/store/categories?categorie=cosmetique" class="active">Cosmétiques</a></li>
                            {% else %}
                            <li class="scroll-to-section"><a href="/store/categories?categorie=cosmetique">Cosmétiques</a></li>
                            {% endif %}
                            {% if categorie == "bijoux" %}
                            <li class="scroll-to-section"><a href="/store/categories?categorie=bijoux" class="active">Bijoux</a></li>
                            {% else %}
                            <li class="scroll-to-section"><a href="/store/categories?categorie=bijoux">Bijoux</a></li>
                            {% endif %}
                            {% if categorie == "enfant" %}
                            <li class="scroll-to-section"><a href="/store/categories?categorie=enfant" class="active">Enfants</a></li>
                            {% else %}
                            <li class="scroll-to-section"><a href="/store/categories?categorie=enfant">Enfants</a></li>
                            {% endif %}
                            {% if user.is_authenticated %}
                            <li class="scroll-to-section"><a href="/accounts/logout" >Se déconnecter</a></li>
                            {% else %}
                                {% if connection %}
                                <li class="scroll-to-section"><a href="/accounts/login" class="active">Se connecter</a></li>
                                {% else %}
                                <li class="scroll-to-section"><a href="/accounts/login">Se connecter</a></li>
                                {% endif %}
                            {% endif %}



                            <!-- <li class="submenu">
                                BOUTIQUE
                                <a href="javascript:;">Pages</a>
                                <ul>
                                    <li><a href="about.html">Qui sommes nous</a></li>
                                    <li><a href="contact.html">Contact Us</a></li>
                                </ul>
                            </li> -->
                        </ul>        
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->
    {% block content %}{% endblock %}


    <!-- ***** Footer Start ***** -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                </div>
                <div class="col-lg-3">
                    <h4>Shopping </h4>
                    <ul>
                        {% if categorie %}
                        <li><a href="{% url 'store:index' %}">Accueil</a></li>
                        {% else %}
                        <li><a href="{% url 'store:index' %}" class="active">Accueil</a></li>
                        {% endif %}
                        {% if categorie == "vetement" %}
                        <li><a href="/store/categories?categorie=vetement" class="active">Vêtements</a></li>
                        {% else %}
                        <li><a href="/store/categories?categorie=vetement">Vêtements</a></li>
                        {% endif %}
                        {% if categorie == "cosmetique" %}
                        <li><a href="/store/categories?categorie=cosmetique" class="active">Cosmétiques</a></li>
                        {% else %}
                        <li><a href="/store/categories?categorie=cosmetique">Cosmétiques</a></li>
                        {% endif %}
                        {% if categorie == "bijoux" %}
                        <li><a href="/store/categories?categorie=bijoux" class="active">Bijoux</a></li>
                        {% else %}
                        <li><a href="/store/categories?categorie=bijoux">Bijoux</a></li>
                        {% endif %}
                        {% if categorie == "enfant" %}
                        <li><a href="/store/categories?categorie=enfant" class="active">Enfants</a></li>
                        {% else %}
                        <li><a href="/store/categories?categorie=enfant">Enfants</a></li>
                        {% endif %}
                    </ul>
                </div>
                <div class="col-lg-3">
                    <h4>Liens utiles</h4>
                    <ul>
                        <li><a href="{% url 'store:index' %}">Homepage</a></li>
                        <li><a href="#">Qui sommes nous</a></li>
                        <li><a href="#">Contact Us</a></li>
                    </ul>
                </div>
                <div class="col-lg-3">
                    <h4>Aides &amp; Informations</h4>
                    <ul>
                        <li><a href="#">Aides</a></li>
                        <li><a href="#">FAQ's</a></li>
                    </ul>
                </div>
                <div class="col-lg-12">
                    <div class="under-footer">                        
                        <ul>
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    

    <!-- jQuery -->
    <script src="{% static 'store/js/jquery-2.1.0.min.js' %}"></script>

    <!-- Bootstrap -->
    <script src="{% static 'store/js/popper.js' %}"></script>
    <script src="{% static 'store/js/bootstrap.min.js' %}"></script>

    <!-- Plugins -->
    <script src="{% static 'store/js/owl-carousel.js' %}"></script>
    <script src="{% static 'store/js/accordions.js' %}"></script>
    <script src="{% static 'store/js/datepicker.js' %}"></script>
    <script src="{% static 'store/js/scrollreveal.min.js' %}"></script>
    <script src="{% static 'store/js/waypoints.min.js' %}"></script>
    <script src="{% static 'store/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'store/js/imgfix.min.js' %}"></script> 
    <script src="{% static 'store/js/slick.js' %}"></script> 
    <script src="{% static 'store/js/lightbox.js' %}"></script> 
    <script src="{% static 'store/js/isotope.js' %}"></script> 
    
    <!-- Global Init -->
    <script src="{% static 'store/js/custom.js' %}"></script>

    <script>

        $(function() {
            var selectedClass = "";
            $("p").click(function(){
            selectedClass = $(this).attr("data-rel");
            $("#portfolio").fadeTo(50, 0.1);
                $("#portfolio div").not("."+selectedClass).fadeOut();
            setTimeout(function() {
              $("."+selectedClass).fadeIn();
              $("#portfolio").fadeTo(50, 1);
            }, 500);
                
            });
        });

    </script>

  </body>
</html>

core/store/templates/store/categorie.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}
<script>
    
    function addType(type) {
        var url = new URL(window.location.href);
        if (url.searchParams.has('type')) {
            url.searchParams.delete('type')
        }
        url.searchParams.append('type', type);
        window.location.replace(url);

        return false
    }
    function addCouleur(Couleur) {

        var url = new URL(window.location.href);
        if (url.searchParams.has('Couleur')) {
            url.searchParams.delete('Couleur')
        }
        url.searchParams.append('Couleur', Couleur);
        window.location.replace(url);

        return false
    }
</script> 
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>

<div class="container">
    <div class="row">
        <div class="col-12">
            <nav class="main-nav">
                <!-- ***** Logo Start ***** -->
                <a href="index.html" class="logo_update">
                    <img src="{% static 'store/images/logo_carre.png' %}">
                </a>
                <!-- ***** Logo End ***** -->
                <!-- ***** Menu Start ***** -->
               
                <!-- ***** Menu End ***** -->
            </nav>
        </div>
    </div>
</div>
    <!-- ***** Main Banner Area Start ***** -->
    <div class="page-heading" id="top"  style="background-image: url(/media/{{background}})">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="inner-content">
                        <span>{{categorie.description}}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- ***** Main Banner Area End ***** -->


    <!-- ***** Products Area Starts ***** -->
   
    <section class="section" id="products">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-heading">
                        <h2>Nos derniers produits</h2>
                    </div>
                </div>
            </div>
        </div>

        <nav class="navbar navbar-expand-lg navbar-white  bg-light">
            <div class="container-fluid justify-content-start">

                <div class="dropdown pr-3">
                    <button class="btn btn-secondary dropdown-toggle " type="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Types de vetements
                    </button>
                    <ul class="dropdown-menu">
                        {% for object in objects %}
                      <li><a  onclick="addType('{{object.id}}'); return false;" class="dropdown-item" href="">{{object.name}}</a></li>
                          {% endfor %}

                    </ul>
                  </div>
                  <div class="dropdown pr-3">
                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Couleurs
                    </button>
                    <ul class="dropdown-menu">
                        {% for couleur in couleurs %}
                      <li><a  onclick="addCouleur('{{couleur.id}}'); return false;" class="dropdown-item" href="">{{couleur.name}}</a></li>
                          {% endfor %}

                    </ul>
                  </div>
                  
                  
            </div>
          </nav>
    </br>
        <div class="container">
            <div class="row">
                <!----->
                {% for item in articles %}
                <div class="col-lg-4">
                    <div class="item">
                        <div class="thumb">
                            <div class="hover-content">
                                <ul>
                                    <li><a href="{% url 'store:detail' item.id %}"><i class="fa fa-eye"></i></a></li>
                                    <!-- <li><a href="single-product.html"><i class="fa fa-star"></i></a></li> -->
                                    <!-- <li><a href="single-product.html"><i class="fa fa-shopping-cart"></i></a></li> BOUTIQUE -->
                                </ul>
                            </div>
                            <img src="/media/{{item.image}}" alt="">
                        </div>
                        <div class="down-content">
                            <h4>{{item.name}}</h4>
                            <span>{{item.prix}} DZ</span>
                            <ul class="stars">
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                            </ul>
                        </div>
                    </div>
                </div>
                {% endfor %}
      
                <!-- <div class="col-lg-12">
                    <div class="pagination">
                        <ul>
                            <li>
                                <a href="#">1</a>
                            </li>
                            <li class="active">
                                <a href="#">2</a>
                            </li>
                            <li>
                                <a href="#">3</a>
                            </li>
                            <li>
                                <a href="#">4</a>
                            </li>
                            <li>
                                <a href="#">></a>
                            </li>
                        </ul>
                    </div>
                </div> -->
            </div>
        </div>
    </section>
    <!-- ***** Products Area Ends ***** -->

{% endblock %}

core/store/templates/store/create.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}
{% load bootstrap5 %}
<div class="page-heading" id="top">

<div class="container">

            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" value="Enregistrer" class="btn btn-primary">
            </form>

</div>
</div>
{% endblock %}

core/store/templates/store/detail.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}


    <!-- ***** Main Banner Area End ***** -->


    <!-- ***** Product Area Starts ***** -->
    <div class="page-heading" id="top">
    <section class="section" id="product">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                <div class="left-images">
                    <img src="/media/{{article.image}}" alt="">
                </div>
            </div>
            <div class="col-lg-4">
                <div class="right-content">
                    <h4>{{article.name}}</h4>
                    <span class="price">{{article.prix}} DZ</span>
                    <!-- <ul class="stars">
                        BOUTIQUE
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                    </ul> -->
                    <span>{{article.description}}</span>
                    <div class="quote">
                        <i class="fa fa-quote-left"></i><p>{{article.description}}</p>
                    </div>
                    <div class="quantity-content">
                        <div class="left-content">
                            <h6>Tailles disponible :</h6>
                            {% for size in sizes%}
                            <h6><span class="badge text-secondary badge-light"> {{size}}</span></h6>
                            {% endfor %}
                        </div>

                    </div>
                    <!-- <div class="total">
                        <h4>Total: $210.00</h4>
                        <div class="main-border-button"><a href="#">Add To Cart</a></div>
                        BOUTIQUE
                    </div> -->
                </div>
            </div>
            </div>
        </div>
    </section>
    <!-- ***** Product Area Ends ***** -->
</div>
{% endblock %}